---
- name: Guest Creation
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }}
      vmware_guest:
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        validate_certs: no 
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        networks:          
        - name: "{{ network }}"
          type: static
          ip: "{{ ip }}"
          netmask: "{{ netmask }}"
          gateway: "{{ gateway }}"
          dns_servers: 
          - "{{ dns_server01 }}"
          - "{{ dns_server02 }}"
        customization:
          dns_servers: 
            - "{{ dns_server01 }}"
            - "{{ dns_server02 }}"
        cluster: "{{ cluster }}"
        state: poweredon
        wait_for_ip_address: yes        
      delegate_to: localhost
      register: vm_result
    
    # - name: gather list
    #   set_fact:
    #     vmlist: "{{ lookup('env','vcenter_host') }}"

    # - debug:
    #     var: vars.groups.all

    - name: IP address info
      debug:
        msg: "{{ vm_result.instance.ipv4 }}"