---
- name: Take Snapshot
  gather_facts: yes
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Create a virtual machine {{ vm_name }} snapshot name {{ snapshot }}
      vmware_guest_snapshot:
        name: "{{ vm_name }}"
        hostname: "{{ vcenter_server }}"
        validate_certs: False
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        snapshot_name: "snapshot-{{ ansible_date_time.iso8601_basic_short }}"
      register: snapshot_result
  
    - name: Assert that VM snapshot is created
      assert:
        that:
          - "snapshot_result.changed"