---
- name: Deploy code
  gather_facts: yes
  hosts: develop
  vars_files:
    - vm_vars.yml
  tasks:   
    - ping:

    - name: Comprobando que exista el directorio
      file:
        dest: "{{ git_folder }}"
        state: directory
        mode: "u=rwx,g=rx,o=rx"
        recurse: yes        

    - stat:
        path: "{{ git_folder }}/index.html"
      register: st

    - name: Clone git
      git:
        repo: 'https://github.com/Felarof23/simple-web.git'
        dest: "{{ git_folder }}"
        clone: yes
      when: not st.stat.exists
    
    - name: Update code
      git:
        repo: 'https://github.com/Felarof23/simple-web.git'
        dest: "{{ git_folder }}"
        update: yes
        force: yes

    - name: restart apache2 service
      service:
        name: httpd
        state: restarted