---
- name: Deploy code
  gather_facts: no
  hosts: localhost
  tasks:   
    - name: Comprobando que exista el directorio
      file:
        dest: /var/www/html
        state: directory
        mode: "u=rwx,g=rx,o=rx"
        recurse: yes        

    - stat:
        path: /var/www/html/index.html
      register: st

    - name: Clone git
      git:
        repo: 'https://github.com/Felarof23/simple-web.git'
        dest: /var/www/html
        clone: yes
      when: not st.stat.exists
    
    - name: Update code
      git:
        repo: 'https://github.com/Felarof23/simple-web.git'
        dest: /var/www/html
        update: yes

    - name: restart apache2 service
      service:
        name: httpd
        state: restarted